openapi: 3.0.3
info:
  version: 1.0.0
  title: API
servers:
  - url: 'http://localhost:3000/api'
components:
  schemas:
    Project:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 50
